sudo: required
dist: trusty
language: python
addons:
  apt:
    packages:
      - llvm-3.6
      - llvm-3.6-dev
      - libedit-dev
env:
  - LLVM_CONFIG=/usr/bin/llvm-config-3.6
install:
  - pip install -r requirements.txt
  - pip install tox
script:
  - tox

